---
# install node-exporter and setup user/groups
- name: Create the node_exporter group
  group:
    name: "{{ node_exporter_system_group }}"
    #system users will have a lower uid number in ps vs a regular user
    state: present
    system: true
  #when: node_exporter_system_group != "root"

- name: Create the node_exporter user
  user:
    name: "{{ node_exporter_system_user }}"
    groups: "{{ node_exporter_system_group }}"
    append: true
    #no shell for this user as it is not intended to login, polite msg displays at login attempt 'This account is currently unavailable.'
    shell: /usr/sbin/nologin
    #system user to signify purpose for the account, this is not a regular user account
    system: true
    #no home directory will be created
    createhome: false
    home: /
  #when: node_exporter_system_user != "root"

- name: Download node_exporter binary to local folder
  become: false
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    checksum: "sha256:{{ node_exporter_checksum }}"
  #save result of get_url
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  #will be run on the machine running ansible?
  delegate_to: localhost
  #if running in check mode, this will run normally even in simulation
  check_mode: false

- name: Unpack node_exporter binary
  become: false
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
  delegate_to: localhost
  check_mode: false

- name: Create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Copy in node_exporter binaries
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: 0755
    #name of user that should own the file/directory
    owner: root
    #name of group that should own the file/directory
    group: root
  #when the above files have changed, restart node_exporter handler
  notify: restart node_exporter
  #when we are not in check mode, running a simulation
  when: not ansible_check_mode