---
prometheus_version: 2.11.1

prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus

prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_port: "9090"
prometheus_storage_retention: "30d"
prometheus_static_targets_file: "prometheus-config.yml"