---
#this is excuted when notified that the binaries for node_exporter have changed
- name: restart node_exporter
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted